spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://192.168.10.229:3306/board?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
#    url: jdbc:mysql://192.168.10.229:3306/board?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ezpmp
    password: dlwmvldpavl
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379


mybatis:
  mapper-locations: mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 1020

ezpmp:
  swagger:
    base-package: "com.edmp.api.board"
    enabled: true
  redis: ### Redis 설정
    holdingTime: '1'
    enabled: true
    host: 210.179.122.170
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
